project:
  type: book
  output-dir: docs
book:
  title: "eprsol"
  author: "Norah Jones"
  date: "1/3/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
always_allow_html: yes
urlcolor: blue
toc-title: Sumário
lang: pt-BR
language:
  ui:
    chapter_name: "Capítulo "
  label:
    fig: "Figura "
    tab: "Tabela "

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
  pdf:
    documentclass: scrreprt
    highlight-style: tango
    toc: true
    toc_depth: 3
    number_sections: true
    extra_dependencies: flafter
    highlight: tango
    includes:
     in_header: preamble.txe
editor: visual

