<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Ecologia de Paisagems com R: soluções - 3&nbsp; Capítulo Respostas multiescala de espécies</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./solutions02_metricas.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./solutions01_escala.html">Soluções</a></li><li class="breadcrumb-item"><a href="./solutions03_especies.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capítulo Respostas multiescala de espécies</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Ecologia de Paisagems com R: soluções</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/darrennorris/eprsol" title="GitHub codigo fonte" class="quarto-navigation-tool px-1" aria-label="GitHub codigo fonte"><i class="bi bi-github"></i></a>
    <a href="./Ecologia-de-Paisagems-com-R--soluções.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bem-vindos</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Apresentação</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introdução</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Soluções</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions01_escala.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Capítulo Escala</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions02_metricas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Capítulo Métricas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions03_especies.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capítulo Respostas multiescala de espécies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sumário</h2>
   
  <ul>
<li>
<a href="#pergunta-1" id="toc-pergunta-1" class="nav-link active" data-scroll-target="#pergunta-1"><span class="header-section-number">3.1</span> Pergunta 1</a>
  <ul class="collapse">
<li><a href="#resposta" id="toc-resposta" class="nav-link" data-scroll-target="#resposta"><span class="header-section-number">3.1.1</span> resposta</a></li>
  </ul>
</li>
  <li>
<a href="#pergunta-2" id="toc-pergunta-2" class="nav-link" data-scroll-target="#pergunta-2"><span class="header-section-number">3.2</span> Pergunta 2</a>
  <ul class="collapse">
<li><a href="#resposta-1" id="toc-resposta-1" class="nav-link" data-scroll-target="#resposta-1"><span class="header-section-number">3.2.1</span> resposta</a></li>
  </ul>
</li>
  <li>
<a href="#pergunta-3" id="toc-pergunta-3" class="nav-link" data-scroll-target="#pergunta-3"><span class="header-section-number">3.3</span> Pergunta 3</a>
  <ul class="collapse">
<li><a href="#resposta-2" id="toc-resposta-2" class="nav-link" data-scroll-target="#resposta-2"><span class="header-section-number">3.3.1</span> resposta</a></li>
  </ul>
</li>
  <li>
<a href="#pergunta-4" id="toc-pergunta-4" class="nav-link" data-scroll-target="#pergunta-4"><span class="header-section-number">3.4</span> Pergunta 4</a>
  <ul class="collapse">
<li><a href="#resposta-3" id="toc-resposta-3" class="nav-link" data-scroll-target="#resposta-3"><span class="header-section-number">3.4.1</span> resposta</a></li>
  </ul>
</li>
  <li>
<a href="#pergunta-5" id="toc-pergunta-5" class="nav-link" data-scroll-target="#pergunta-5"><span class="header-section-number">3.5</span> Pergunta 5</a>
  <ul class="collapse">
<li><a href="#resposta-4" id="toc-resposta-4" class="nav-link" data-scroll-target="#resposta-4"><span class="header-section-number">3.5.1</span> resposta</a></li>
  </ul>
</li>
  <li>
<a href="#pergunta-6" id="toc-pergunta-6" class="nav-link" data-scroll-target="#pergunta-6"><span class="header-section-number">3.6</span> Pergunta 6</a>
  <ul class="collapse">
<li><a href="#resposta-5" id="toc-resposta-5" class="nav-link" data-scroll-target="#resposta-5"><span class="header-section-number">3.6.1</span> resposta</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capítulo Respostas multiescala de espécies</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>Carregar os pacotes necessarios:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://darrennorris.github.io/eprdados/">eprdados</a></span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="pergunta-1" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="pergunta-1">
<span class="header-section-number">3.1</span> Pergunta 1</h2>
<p><span style=" font-weight: bold;    color: blue !important;">Verificar os dados entrevistas e carnivoros, usando funções "class()"; "str()" e ajudar "?". Descreva o conteúdo e compare as diferenças nesses dois conjuntos de dados. </span></p>
<section id="resposta" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="resposta">
<span class="header-section-number">3.1.1</span> resposta</h3>
<p>Para responder a pergunta você deve revisar os exemplos no capítulo.</p>
<p>Carregar os dados:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">entrevistas</span> <span class="op">&lt;-</span> <span class="fu">eprdados</span><span class="fu">::</span><span class="va"><a href="https://darrennorris.github.io/eprdados/reference/entrevistas.html">entrevistas</a></span></span>
<span><span class="va">carnivoros</span> <span class="op">&lt;-</span> <span class="fu">eprdados</span><span class="fu">::</span><span class="va"><a href="https://darrennorris.github.io/eprdados/reference/carnivoros.html">carnivoros</a></span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Identifique e compare os tipos de objeto:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">entrevistas</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "tbl_df"     "tbl"        "data.frame"</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">carnivoros</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>Comparando os dois objetos vemos que o objeto <code>entrevistas</code> possui mais classes que o <code>carnivoros</code>. A <code><a href="https://rdrr.io/r/base/class.html">class()</a></code> nos conta o que podemos fazer com os objetos em R. As entrevistas são uma classe <a href="https://r-spatial.github.io/sf/articles/">sf</a>, que é um vetor espacial - assim sendo possamos:</p>
<ul>
<li><p>fazer <a href="https://r-spatial.github.io/sf/articles/sf5.html">mapas</a> : <a href="https://r-spatial.github.io/sf/articles/sf5.html" class="uri">https://r-spatial.github.io/sf/articles/sf5.html</a> .</p></li>
<li><p>executar análises espaciais, como calcular <a href="https://darrennorris.github.io/epr/cap02.html">métricas de paisagem</a> : <a href="https://darrennorris.github.io/epr/cap02.html" class="uri">https://darrennorris.github.io/epr/cap02.html</a> .</p></li>
</ul>
<p>Ambos os objetos são da class “data.frame”. Podemos, portanto, traçar gráficos e construir modelos com os dados de ambos os objetos.</p>
<p>Podemos olhar sobre a estrutura com o codigo a seguir:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">entrevistas</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sf [106 × 3] (S3: sf/tbl_df/tbl/data.frame)
 $ aid        : int [1:106] 1 2 3 4 5 6 7 8 9 10 ...
 $ Habitat_WWF: chr [1:106] "Cerrado" "Cerrado" "Cerrado" "Cerrado" ...
 $ geometry   :sfc_POINT of length 106; first list element:  'XY' num [1:2] -51.1093 -0.0162
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: 3 1
  ..- attr(*, "names")= chr [1:2] "aid" "Habitat_WWF"</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">carnivoros</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2544 obs. of  13 variables:
 $ aid              : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Latitude         : num  -0.0162 -0.0162 -0.0162 -0.0162 -0.0162 ...
 $ Longitude        : num  -51.1 -51.1 -51.1 -51.1 -51.1 ...
 $ Habitat_WWF      : chr  "Cerrado" "Cerrado" "Cerrado" "Cerrado" ...
 $ class            : int  1 1 1 1 1 1 1 1 1 1 ...
 $ class_description: chr  "Forest" "Forest" "Forest" "Forest" ...
 $ metric           : chr  "cpland" "cpland" "cpland" "cpland" ...
 $ buff_dist_km     : num  0.125 0.25 0.5 1 16 2 4 8 0.125 0.25 ...
 $ buff_metric      : chr  "cpland_0.125" "cpland_0.25" "cpland_0.5" "cpland_1" ...
 $ value_median     : num  3.23 34.58 51.11 47.51 22.7 ...
 $ sp_name          : chr  "sppB" "sppB" "sppB" "sppB" ...
 $ sp_ab            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ sp_pa            : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<p>Usando a função <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> nos mostra que entrevistas possui 106 linhas (uma linha para cada propriedade) e o carnivoros possui 2544 linhas (106 propriedades vezes 8 distâncias de buffer vezes 3 espécies de carnívoros). Vemos também que o objeto carnivoros possui mais colunas, com informações sobre as propriedades, espécies e métricas da paisagem. É interessante que isso inclua colunas com coordenadas geográficas, mas o objeto não é espacial.</p>
</section></section><section id="pergunta-2" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="pergunta-2">
<span class="header-section-number">3.2</span> Pergunta 2</h2>
<p><span style=" font-weight: bold;    color: blue !important;">Na aula "Organização de paisagens" vimos que as paisagens contemporâneas são uma resultado de i) variabilidade em condições abióticos; ii) interações bióticas; iii) distúrbios naturais e sucessão; e iv) padrões antrópicos no uso da terra. Usando Google Earth Timelapse e a forma interativa da mapview, verficar a paisagem acerca das propriadades. Com base na sua interpretação das mapas, as aulas, e literatura citado até agora (como Michalski et. al.&nbsp;2020, Michalski &amp; Peres 2005, Michalski &amp; Peres 2007), apresentar trés fatores que poderia explicar a distribuição espacial de especies de mamiferos na paisagem. Para cada fator inclui uma hipotese valida (e não trivial) junto com uma previsão que pode se testado com um estudo de Ecologia da Paisagem.</span></p>
<section id="resposta-1" class="level3" data-number="3.2.1"><h3 data-number="3.2.1" class="anchored" data-anchor-id="resposta-1">
<span class="header-section-number">3.2.1</span> resposta</h3>
<p>Para desenvolver a sua resposta, você deve olhar para exemplos de mamíferos que ocorrem na área de estudo <span class="citation" data-cites="Michalski2020int">(<a href="references.html#ref-Michalski2020int" role="doc-biblioref">Michalski et al. 2020</a>)</span>. Em seguida, identifique os fatores que são conhecidos por serem importantes para diferentes espécies <span class="citation" data-cites="MICHALSKI2005383 MICHALSKI2007conbio regolin2017forest">(<a href="references.html#ref-MICHALSKI2005383" role="doc-biblioref">Michalski e Peres 2005</a>, <a href="references.html#ref-MICHALSKI2007conbio" role="doc-biblioref">2007</a>; <a href="references.html#ref-regolin2017forest" role="doc-biblioref">Regolin et al. 2017</a>)</span>. O que é apresentado aqui é uma estrutura fundamental. Use os exemplos para desenvolver suas próprias respostas.</p>
<section id="exemplos-de-fatores" class="level4" data-number="3.2.1.1"><h4 data-number="3.2.1.1" class="anchored" data-anchor-id="exemplos-de-fatores">
<span class="header-section-number">3.2.1.1</span> Exemplos de fatores</h4>
<p>Sabemos que os padrões na distribuição e abundância dos mamíferos respondem a uma variedade de diferentes características das paisagens. Olhando para os mapas podemos identificar vários fatores potencialmente importantes. Abaixo está uma lista com alguns exemplos. Esta não é uma lista completa e não representa necessariamente os fatores mais importantes.</p>
<ol type="1">
<li>Variabilidade em condições abióticos:<br>
São aqueles relacionados ao ambiente físico, como clima, solo e topografia. Há muito pouca variação de altitude na área de estudo. Sabemos que os mamíferos são endotérmicos e, que em torno do equador há pouca variação climática num espaço do tamanho da área de estudo. Portanto, é muito pouco provável que o clima e altitude afecte os padrões dos mamíferos na área de estudo.
<ul>
<li>Proximidade com o rio Amazonas.</li>
</ul>
</li>
<li>Interações bióticas:<br>
São aqueles relacionados às interações entre os organismos, como predação, competição e mutualismo.
<ul>
<li>Predação. A presença de predadores pode limitar a abundância de presas, como veados e capivaras.</li>
<li>Interferência competitiva (interference competition), que ocorre quando indivíduos de espécies diferentes competem diretamente por recursos. Por exemplo, um gato-maracajá (<em>Leopardus wiedii</em>), um predador especialista e ágil de pequenas presas arbóreas, pode ser forçada a abandonar uma presa recém-capturada por uma jaguatirica (<em>Leopardus pardalis</em>), um predador maior e mais forte. Tais encontros podem limitar o sucesso de alimentação do gato-maracajá e potencialmente restringir a sua distribuição dentro do habitat partilhado.</li>
<li>Liberação de mesopredadores (meso-predator release), em que a remoção de um predador de topo desencadeia consequências não intencionais para níveis tróficos inferiores. Por exemplo, quando a caça humana reduza as populações de onças-pintadas (<em>Panthera onca</em>), as jaguatiricas podem experimentar um aumento na abundância devido à redução da competição intraespecífica e da pressão de predação. No entanto, isso pode levar a um efeito dominó, com as populações de jaguatiricas aumentando e exercendo pressão crescente sobre presas menores, como roedores e aves. Isso perturba a teia alimentar do ecossistema e pode ter efeitos cascateantes nas comunidades de plantas e na biodiversidade geral.</li>
</ul>
</li>
<li>Distúrbios naturais e sucessão:<br>
podem criar oportunidades para a colonização de novas áreas ou, por outro lado, podem levar à extinção de espécies.
<ul>
<li>Incêndios florestais.</li>
<li>Inundações.</li>
<li>Ecótonos e áreas de transição entre diferentes tipos de habitats.</li>
<li>Áreas que foram desmatadas, mas foram abandonadas e estão retornando à natureza.</li>
</ul>
</li>
<li>Padrões antrópicos no uso da terra:<br>
São aqueles relacionados às atividades humanas, como desmatamento, agricultura, caça e mineração.
<ul>
<li>Estradas.</li>
<li>Centros urbanos.</li>
<li>Casas.</li>
<li>Uso da terra - agricultura.</li>
<li>Perda de cobertura natural da terra.</li>
</ul>
</li>
</ol></section><section id="exemplos-de-hipótese" class="level4" data-number="3.2.1.2"><h4 data-number="3.2.1.2" class="anchored" data-anchor-id="exemplos-de-hipótese">
<span class="header-section-number">3.2.1.2</span> Exemplos de hipótese</h4>
<p>Existem centenas de hipóteses ecológicas potencialmente relevantes. Krebs (1972) sugeriu que: ‘Ecologia é o estudo científico das interações que determinam a distribuição e abundância dos organismos’. Como tal, existe uma componente espacial associada a muitas (se não à maioria) das hipóteses ecológicas. São listados alguns exemplos que foram aplicados no contexto da ecologia da paisagem. Esta não é uma lista completa e é usada para fornecer exemplos ilustrativos.</p>
<p>A distribuição espacial e a abundância de mamíferos estão intrinsecamente ligadas a diversas características da paisagem, abrangendo condições abióticas, interações biológicas, perturbações e sucessão naturais e pressões induzidas pelo homem.</p>
<ol start="2" type="1">
<li>
<p>Interações bióticas:<br></p>
<ul>
<li>Predação.</li>
<li>Presa. Hipótese de alocação de risco (risk allocation hypothesis).</li>
</ul>
</li>
<li><p>Distúrbios naturais e sucessão:&nbsp;<br>
Distúrbios naturais e processos de sucessão moldam as comunidades de mamíferos. A Hipótese de Perturbação Intermediária (Intermediate Disturbance Hypothesis) propõe que níveis moderados de perturbação maximizam a biodiversidade. Pesquisas nas savanas brasileiras apoiam essa hipótese, com estudos indicando que frequências intermediárias de incêndios aumentam a diversidade de plantas e pequenos mamíferos.</p></li>
<li><p>Padrões antrópicos no uso da terra:&nbsp;<br>
Nas últimas duas décadas, os ecologistas adotaram o conceito de “paisagem do medo” (landscapes of fear) para descrever a variação espacial no risco de predação conforme percebido pelas presas em toda a sua área de alimentação ou área de vida <span class="citation" data-cites="gaynor2019landscapes">(<a href="references.html#ref-gaynor2019landscapes" role="doc-biblioref">Gaynor et al. 2019</a>)</span>. Este conceito baseia-se nas disciplinas de ecologia comportamental, populacional, comunitária e espacial para considerar o papel do risco de predação espacialmente heterogêneo na condução do comportamento das presas e das cascatas tróficas. O termo “paisagem do medo” foi cunhado por Laundré e colegas em 2001 em seu artigo sobre vigilância de veados e bisões e comportamento de forrageamento em resposta à reintrodução de lobos em Yellowstone. Os humanos remodelam paisagens de medo através da remoção e reintrodução de predadores, modificação de habitat e intensificação de atividades como caça e recreação. Predadores invasores ou mudanças de habitat induzidas pelo homem podem criar armadilhas ecológicas, nas quais as presas não conseguem otimizar o comportamento devido a paisagens anacrónicas de medo. Os humanos também representam um novo “superpredador” de ponta. Em locais onde há caça, a atividade humana letal cria paisagens de medo potencialmente novas para as espécies-alvo, com possíveis consequências para a fisiologia, a demografia das presas e a estrutura das comunidades humanos-naturais. No entanto, os animais percebem o risco dos humanos mesmo na ausência de reforço letal, e as paisagens antropogénicas de medo têm sido associadas a consequências demográficas. A importância relativa da paisagem do medo na formação da dinâmica populacional e das interacções entre espécies varia entre sistemas, e a actividade humana está a alterar e a criar novas paisagens de medo para os animais selvagens. Este é apenas um exemplo de como as hipóteses estão indo além da fragmentação florestal e dos limiares nos padrões espaciais.</p></li>
</ol></section></section></section><section id="pergunta-3" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="pergunta-3">
<span class="header-section-number">3.3</span> Pergunta 3</h2>
<p><span style=" font-weight: bold;    color: blue !important;">Identifique a espécie "sppD". Com base nos resultados dos boxplots e os artigos (Michalski &amp; Peres 2005; Michalski &amp; Peres 2007, Regolin et. al.&nbsp;2017), sugerem três espécies de carnívoros que poderiam apresentar os mesmos padrões do sppD? Que informações/resultados adicionais o ajudariam a identificar a espécie sppD com maior certeza? Justifique suas escolhas em uma forma clara e concisa.</span></p>
<section id="resposta-2" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="resposta-2">
<span class="header-section-number">3.3.1</span> resposta</h3>
<p>Os boxplots mostram que, em média, onde a espécie está presente há mais cobertura florestal. Portanto, as espécies potenciais serão três daquelas que mostram uma relação positiva com a cobertura florestal/tamanho da mancha florestal.</p>
<p>Para podermos identificar com maior certeza precisamos de mais detalhes sobre a taxonomia (que tipo de carnívoro - Canidae, Felidae, Mephitidae, Mustelidae ou Procyonidae) e características funcionais como tamanho corporal e área de vida. Além disso, mais dados sobre como a distribuição das espécies muda com os padrões da paisagem – sabemos que existe uma relação positiva com floresta, mas não sabemos mais nada. Por exemplo, poderíamos ser mais precisos se soubéssemos quão forte é a relação ou se é linear ou não.</p>
</section></section><section id="pergunta-4" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="pergunta-4">
<span class="header-section-number">3.4</span> Pergunta 4</h2>
<p><span style=" font-weight: bold;    color: blue !important;">O que sabemos sobre a espécie "sppD"? Com base nos resultados obtidos: boxplots, graficos com a relação entre occorencia e proporção de floresta, resultados sobre escala do efeito e os artigos (Michalski &amp; Peres 2005; Michalski &amp; Peres 2007; Regolin et. al.&nbsp;2017), forneça uma caracterização da espécie (por exemplo, especialista/generalistasensível/resiliente). Justifique a sua caracterização e interpretações com resultados específicos, destacando os resultados com maior relevância. Que informações/resultados adicionais o ajudariam a caracterizar a espécie sppD com maior certeza? Justifique suas escolhas de forma clara e concisa.</span></p>
<section id="resposta-3" class="level3" data-number="3.4.1"><h3 data-number="3.4.1" class="anchored" data-anchor-id="resposta-3">
<span class="header-section-number">3.4.1</span> resposta</h3>
<p>Para responder a esta pergunta, você precisa resumir os resultados. Isto pode ser feito de diferentes maneiras, por exemplo, comece com o resultado mais geral e importante e depois siga uma sequência lógica até o mais específico.</p>
<ol type="1">
<li><p>Todas as análises e resultados mostram que a presença de sppD tem uma forte relação positiva com a cobertura florestal.</p></li>
<li><p>A análise da escala de efeito mostrou que na escala de 1 km a sppD estava presente quando havia em media aproximadamente 78% de cobertura florestal (boxplots). O modelo de regressão logística nesta mesma escala mostrou que foi obtida uma probabilidade de ocorrência de 50% com aproximadamente 70% de cobertura florestal.</p></li>
<li><p>Todas as análises e resultados mostram variação na relação em diferentes escalas. Usando modelos de regressão logística para identificar a escala do efeito da cobertura florestal na ocorrência de sppD, identificamos a escala de 1km como a mais importante e útil. Os resultados do modelo nesta escala tiveram a maior log-verossimilhanças e o maior desvio explicado.</p></li>
<li><p>Todos os resultados mostraram muitas variações inexplicáveis nos padrões de ocorrência nas 106 propriedades. Boxplots mostraram que a cobertura florestal não explicou a variação nas ausências. Usando modelos de regressão logística descobrimos que o melhor modelo (escala de 1km) explicou cerca de 37% do desvio nos dados.</p></li>
</ol>
<p>A identificação de espécies de carnívoros na paisagem é uma tarefa complexa que pode ser dificultada pela falta de dados. Para podermos identificar a espécie “sppD” com maior certeza, precisamos de mais informações sobre sua taxonomia (que tipo de carnívoro é - Canidae, Felidae, Mephitidae, Mustelidae ou Procyonidae), características funcionais (como tamanho corporal e área de vida) e distribuição espacial.</p>
<p>A distribuição espacial da espécie é um fator importante a ser considerado. Sabemos que a “sppD” está associada à floresta, mas não sabemos como sua distribuição (principalmente as ausências) é afetada por outros fatores, como os impactos humanos. A inclusão de variáveis adicionais para representar outros fatores, como os impactos humanos, pode melhorar o modelo de distribuição da espécie e fornecer estimativas mais precisas da escala do efeito.</p>
</section></section><section id="pergunta-5" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="pergunta-5">
<span class="header-section-number">3.5</span> Pergunta 5</h2>
<p><span style=" font-weight: bold;    color: blue !important;">O que sabemos sobre as três espécies de carnívoros? Com base nos resultados obtidos: boxplots, graficos com a relação entre occorencia e proporção de floresta, resultados sobre escala do efeito e os artigos (Michalski &amp; Peres 2005; Michalski &amp; Peres 2007; Regolin et. al.&nbsp;2017), forneça uma identificação (nome científico e nome comum) e caracterização de cada espécie (por exemplo, especialista/generalista/sensível/resiliente). Justifique a sua identificação, caracterização e interpretações com resultados específicos, destacando os resultados com maior relevância. Que informações/resultados adicionais o ajudariam a caracterizar as espécies com maior certeza? Justifique suas escolhas de forma clara e concisa.</span></p>
<section id="resposta-4" class="level3" data-number="3.5.1"><h3 data-number="3.5.1" class="anchored" data-anchor-id="resposta-4">
<span class="header-section-number">3.5.1</span> resposta</h3>
<p>Use a leitura sugerida e o exemplo de resposta 4 para responder a esta pergunta.</p>
</section></section><section id="pergunta-6" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="pergunta-6">
<span class="header-section-number">3.6</span> Pergunta 6</h2>
<p><span style=" font-weight: bold;    color: blue !important;">Vimos como a incerteza quanto à escala do efeito é provavelmente, pelo menos em parte, uma consequência da correlação entre escalas. Também é possível que, além da cobertura florestal, existam outros fatores que afetem a ocorrência das três espécies na paisagem estudada. Usando como base o conteudo das aulas, leitura disponivel no Google Classroom (Base teórica 4 Dados, métricas, analises), e/ou exemplos apresentados aqui no capitulo, apresentam algumas hipóteses alternativas que poderiam explicar a incerteza nos modelos para as três espécies. Forneça recomendações para variáveis adicionais que poderiam ser incluídas nos modelos para testar suas hipóteses. Justifique sua seleção de forma clara e concisa, apoie sua escolha com exemplos da literatura científica.</span></p>
<section id="resposta-5" class="level3" data-number="3.6.1"><h3 data-number="3.6.1" class="anchored" data-anchor-id="resposta-5">
<span class="header-section-number">3.6.1</span> resposta</h3>
<p>Use a leitura sugerida e o exemplos de respostas anteriores para responder a esta pergunta.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-gaynor2019landscapes" class="csl-entry" role="listitem">
Gaynor, Kaitlyn M, Joel S Brown, Arthur D Middleton, Mary E Power, e Justin S Brashares. 2019. <span>“Landscapes of fear: spatial patterns of risk perception and response”</span>. <em>Trends in ecology &amp; evolution</em> 34 (4): 355–68. <a href="https://doi.org/10.1016/j.tree.2019.01.004">https://doi.org/10.1016/j.tree.2019.01.004</a>.
</div>
<div id="ref-Michalski2020int" class="csl-entry" role="listitem">
Michalski, Fernanda, Ricardo Luiz Pires Boulhosa, Yuri Nascimento do Nascimento, e Darren Norris. 2020. <span>“Rural Wage-Earners’ Attitudes Towards Diverse Wildlife Groups Differ Between Tropical Ecoregions: Implications for Forest and Savanna Conservation in the Brazilian Amazon”</span>. <em>Tropical Conservation Science</em> 13: 1940082920971747. <a href="https://doi.org/10.1177/1940082920971747">https://doi.org/10.1177/1940082920971747</a>.
</div>
<div id="ref-MICHALSKI2005383" class="csl-entry" role="listitem">
Michalski, Fernanda, e Carlos A. Peres. 2005. <span>“Anthropogenic determinants of primate and carnivore local extinctions in a fragmented forest landscape of southern Amazonia”</span>. <em>Biological Conservation</em> 124 (3): 383–96. <a href="https://doi.org/10.1016/j.biocon.2005.01.045">https://doi.org/10.1016/j.biocon.2005.01.045</a>.
</div>
<div id="ref-MICHALSKI2007conbio" class="csl-entry" role="listitem">
———. 2007. <span>“Disturbance-Mediated Mammal Persistence and Abundance-Area Relationships in Amazonian Forest Fragments”</span>. <em>Conservation Biology</em> 21 (6): 1626–40. <a href="https://doi.org/10.1111/j.1523-1739.2007.00797.x">https://doi.org/10.1111/j.1523-1739.2007.00797.x</a>.
</div>
<div id="ref-regolin2017forest" class="csl-entry" role="listitem">
Regolin, André Luis, Jorge José Cherem, Maurı́cio Eduardo Graipel, Juliano André Bogoni, John Wesley Ribeiro, Maurı́cio Humberto Vancine, Marcos Adriano Tortato, et al. 2017. <span>“Forest cover influences occurrence of mammalian carnivores within Brazilian Atlantic Forest”</span>. <em>Journal of Mammalogy</em> 98 (6): 1721–31. <a href="https://doi.org/10.1093/jmammal/gyx103">https://doi.org/10.1093/jmammal/gyx103</a>.
</div>
</div>
</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./solutions02_metricas.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Capítulo Métricas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>